### PR TITLE
Add optional arg to init(), for a function to run after a test failure

### PR DESCRIPTION
**Pull request by robert-iddink**

### CODE REVIEW

**Comment by pmowrer** [comment]
Thanks for the contribution @Arzie! What's the use case for this?

**Comment by robert-iddink** [comment]
We're using it to keep the browser open for a few seconds when a test fails, so we're able to see where it went wrong.

**Comment by pmowrer** [comment]
Have you tried using Protractor's `onComplete`, `onCleanUp` or `afterLaunch` hooks to do this? 

https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L263

**Comment by robert-iddink** [comment]
I have tried writing my own custom reporter, but haven't tried the methods you suggest. Will do and get back to you, thanks!

**Comment by robert-iddink** [comment]
`onComplete` was the one that worked (the others run after the browser has been closed). Apparently it is passed an argument which indicates if the tests ran successfully (didn't see that in the docs):

```
onComplete: function(success) {
        if (!success) {
            console.log('\nThere is a test failure, will sleep for 10 seconds, so you can have a look at what might have gone wrong...');
            // Wait a few seconds, so you can see the error, especially handy in a remote execution
            return browser.sleep(10000);
        }
    }
```

Thanks for your suggestion! I'll close this PR.

**Comment by pmowrer** [comment]
Glad to hear it worked!

**Pull request closed without merging**
